[package]
name = "exchange-autodiscover"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11.20"
rpassword = "7.2.0"
tokio = { version = "1.32.0", features = ["full"] }
xml = "0.8.10"

